### PR TITLE
Convert to noarch

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The used path `${PREFIX}/fonts` is generic for osx, win and linux, so the recipe can be `noarch: generic` without further changes.

See also https://github.com/AnacondaRecipes/aggregate/tree/master/font-ttf-ubuntu-feedstock/recipe

### CODE REVIEW

**Comment by dbast** [comment]
@jan-janssen Ready for review/merge.

**Comment by jan-janssen** [comment]
@dbas Usually these fonts are by default installed in commercial operation systems, therefore this package was originally only created for Linux. Is there a specific reason why you do not want to reference the core fonts? I mean in contrast to libraries fonts are rather static.

**Comment by jan-janssen** [comment]
@bgruening maybe you can also comment on this. Is there any official strategy to handle fonts in conda?

**Comment by dbast** [comment]
Afaik, those fonts are technically not architecture dependant, as they do not contain any compiled code or any other architecture specific things. Which means that this could be a noarch package, same as the referenced AncondaRecipes font ... If there is any benefit installing it on osx/win is a different question.

**Comment by bgruening** [comment]
@jan-janssen this package is or can become part if our official stradegy. Multiple people currently try to make R font aware and there are different options on the table. That said there is no technical reason to not make this package arch dependent imho and if R will depend on it we need to install on OSX/Win as well - no matter if we assume font on those systems.

:+1: from my side.

**Comment by dbast** [comment]
Thanks!

**Pull request merged**
